language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
    - master
    - major-revision

install:
  - pip install -r requirements.txt
  - pip install tensorflow
  - pip install gym
  - pip install .

script:
  - pytest

notifications:
  email:
    recipients:
      - tensorforce.team@gmail.com
    on_success: never
    on_failure: always
