sudo: required
dist: trusty
language: python

services:
  - docker

env:
  - DOCKER_JOB_NAME='tensorforce_pytest'

matrix:
  include:
  - env:
    - DOCKER_IMAGE='tensorflow/tensorflow:latest'
  - env:
    - DOCKER_IMAGE='tensorflow/tensorflow:latest-py3'

before_install:
  - docker pull ${DOCKER_IMAGE}
  - docker run --rm --name ${DOCKER_JOB_NAME} -v $(pwd):/tensorforce ${DOCKER_IMAGE} /bin/bash -c 'while true; do sleep 1; done';

install:
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'python -m pip install -U pip';
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'python -m pip install pytest-xdist';
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'python -m pip install gym';
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'cd /tensorforce && python -m pip install .';

script:
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'cd /tensorforce && python -m pytest';

notifications:
  email:
    recipients:
      - contact@reinforce.io
    on_success: never
    on_failure: always